# Generated by Django 5.1.3 on 2024-12-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='status',
            new_name='status_from_user',
        ),
        migrations.AddField(
            model_name='friendship',
            name='status_to_user',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
